version: '3'
services:
  front:
    container_name: front
    image: front
    build: ./frontend
    restart: always
    networks:
      - ums-user-facing
  back:
    container_name: back
    image: back
    build: ./backend
    environment:
      - UMS_DB_NAME=ums
      - UMS_DB_USERNAME=dev
      - UMS_DB_PASSWORD=devpass
      - UMS_DB_PORT=3306
      - UMS_DB_IP=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ums-user-facing
      - ums-back-office
  db:
    container_name: db
    image: mariadb
    restart: always
    environment:
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devpass
      - MYSQL_ROOT_PASSWORD=devpass
      - MYSQL_DATABASE=ums
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - maria-db:/usr/var/lib/mysql
    networks:
      - ums-back-office
  proxy:
    image: nginx:1.21
    ports:
      - "7887:80"
    depends_on:
      - back
      - front
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - ums-user-facing
volumes:
  maria-db:
    driver: local
networks:
  ums-user-facing:
  ums-back-office:
  


